---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: 10.4.239.2
  port: "5432"
  database: awx
  username: awx
  password: P433w0rd
  sslmode: prefer
  type: unmanaged
type: Opaque
