---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  admin_user: admin
  admin_password_secret: awx-admin-password

  service_type: ClusterIP
  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  bundle_cacert_secret: awx-custom-certs
  hostname: awx-m1.arxus.local

  # ee_pull_credentials_secret: awx-ee-pull-credentials
  # ee_images:
  #   - name: Arxus EE (latest)
  #     image: quay.arxus.local/ansible/ee:2.15-custom

  postgres_configuration_secret: awx-postgres-configuration

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  web_replicas: 2
  task_replicas: 4

  postgres_init_container_resource_requirements: {}
  postgres_resource_requirements: {}
  web_resource_requirements: {}
  task_resource_requirements: {}
  ee_resource_requirements: {}
  init_container_resource_requirements: {}

  # Uncomment to reveal "censored" logs
  no_log: false
