---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cgsa
  namespace: awx
secrets:
  - name: cgsa-secret

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cgsa
  namespace: awx
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cgsa-binding
  namespace: awx
subjects:
  - kind: ServiceAccount
    name: cgsa
    namespace: awx
roleRef:
  kind: Role
  name: role-cgsa
  apiGroup: rbac.authorization.k8s.io
