---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-custom-certs
    files:
      - bundle-ca.crt=rootCA.pem

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=H0st3dAnsible321

resources:
  - aps.yaml
  - cgsa-secret.yaml
  - pullsecret.yaml
  - pv.yaml
  - pvc.yaml
  - containergroup-sa.yaml
  - awx.yaml
