---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  storageClassName: awx-projects-volume
  hostPath:
    path: /var/lib/awx/projects
